# Generated by Django 2.2.2 on 2019-07-08 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_acmodel', models.CharField(max_length=100, verbose_name='基本型号')),
                ('expanded_acmodels', models.CharField(max_length=100, verbose_name='系列号')),
                ('if_intra_ac', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '飞机型号',
                'verbose_name_plural': '飞机型号',
                'ordering': ('basic_acmodel',),
            },
        ),
        migrations.AlterField(
            model_name='term',
            name='acmodel',
            field=models.ForeignKey(limit_choices_to={'if_intra_ac': True}, on_delete=django.db.models.deletion.CASCADE, related_name='适用机型', to='term.acmodel'),
        ),
    ]
