# Generated by Django 2.2.2 on 2019-07-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_auto_20190708_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='acmodel',
            field=models.ForeignKey(limit_choices_to={'if_intra_ac': True}, on_delete=django.db.models.deletion.CASCADE, related_name='适用机型', to='data_platform.acmodel'),
        ),
        migrations.DeleteModel(
            name='acmodel',
        ),
    ]
