# Generated by Django 2.2.2 on 2019-07-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='acmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_acmodel', to='type_data.acmodel'),
        ),
    ]
