# Generated by Django 2.2.2 on 2019-07-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_data', '0002_auto_20190708_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ac',
            name='acmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_acmodel', to='data_platform.acmodel'),
        ),
        migrations.AlterField(
            model_name='fm',
            name='acmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fm_acmodels', to='data_platform.acmodel'),
        ),
        migrations.DeleteModel(
            name='acmodel',
        ),
    ]
