# Generated by Django 2.2.2 on 2019-07-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_acmodel', models.CharField(max_length=100, verbose_name='基本型号')),
                ('expanded_acmodel', models.CharField(max_length=100, verbose_name='扩展型号')),
                ('if_intra_ac', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(default='na', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='data_source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title of data table')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('source_interpretation', models.CharField(max_length=300, verbose_name='Interpretation of the data source')),
                ('acmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_platform.acmodel')),
            ],
        ),
        migrations.CreateModel(
            name='data_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='download file address')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('date', models.DateField(verbose_name='发生时间')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_platform.data_source')),
            ],
        ),
        migrations.CreateModel(
            name='accident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('date', models.DateField(verbose_name='发生时间')),
                ('content', models.TextField(verbose_name='事件描述')),
                ('acmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_platform.acmodel')),
            ],
        ),
    ]
