# Generated by Django 2.2.2 on 2019-07-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmodel',
            options={'ordering': ('basic_acmodel',), 'verbose_name': '飞机型号', 'verbose_name_plural': '飞机型号'},
        ),
    ]
